kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 3000
    hostPort: 3000
    protocol: TCP
  - containerPort: 8500
    hostPort: 8500
    protocol: TCP
  - containerPort: 9090
    hostPort: 9090
    protocol: TCP
