apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consul
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: consul
  namespaceSelector:
    matchNames:
    - consul
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
