# Custom values for kube-prometheus-stack
prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
  service:
    type: NodePort
    port: 9090
    nodePort: 30090
grafana:
  enabled: true
  adminPassword: "admin123"  # Change this in production
  service:
    type: NodePort
    port: 80
    nodePort: 30000 
  readinessProbe:
    initialDelaySeconds: 30  # Wait 30 seconds before starting probes
    timeoutSeconds: 5
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 5
alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
